# https://www.playframework.com/documentation/latest/Configuration
db.default.driver=org.postgresql.Driver
db.default.url = "jdbc:postgresql://localhost:5432/stock_market"
db.default.url = ${?DB_URL}

db.default.username = "simulator_user"
db.default.username = ${?DB_USER}

db.default.password = "simulator_pass"
db.default.password = ${?DB_PASSWORD}

play.evolutions.db.default.autoApply=true
